### ISSUE TITLE
Swap value vs dashboard value discrepancy

### ISSUE THREAD

**Issue by jdmarlow86** [hyperdexapp/hyperdex#379]
The value of my OOT is quite different between the Dashboard view and the Exchange view sell order

![image](https://user-images.githubusercontent.com/22251770/41867253-93aadaf4-7880-11e8-9d72-913d61f1541c.png)
![image](https://user-images.githubusercontent.com/22251770/41867311-c7a461c2-7880-11e8-8ccf-f32b753c352b.png)

Version: alpha 7
OS: Windows 10
Errors: None
Severity: Medium (2)

**Comment by lukechilds** [comment]
Thanks for reporting. I'm unable to re-create:

<img width="787" alt="screen shot 2018-06-26 at 2 21 56 pm" src="https://user-images.githubusercontent.com/2123375/41895619-b6d7d596-794c-11e8-9b2e-2121227fadd3.png">

<img width="300" alt="screen shot 2018-06-26 at 2 23 26 pm" src="https://user-images.githubusercontent.com/2123375/41895620-ba010a58-794c-11e8-9422-52f1412e680e.png">

The USD price you have for OOT is definitely wrong in your dashboard though. It's reporting it as $0.005 when it should be way higher.

We use CMC prices by default, and if they are unavailable, we fallback to the `marketmaker` supplied prices, which are much less reliable due to low volume. It could be that due to connectivity issues you where switching between CMC and `marketmaker` prices. And the `marketmaker` price was just way off.

Are you able to reliably reproduce this issue?

**Comment by jdmarlow86** [comment]
Just tried to reproduce and it looks like it cleared itself up, it can be closed. Thanks!
